import {beforeEach,expect,it,vi} from 'vitest'
import {commerce,type CartLine,type ServerCart,canPay,paymentUrl,type Order} from './api'
import {syncGuestCart} from './cart-sync'
import {useCartStore} from '@/features/store/store/cart-store'
const line=(quantity:number):CartLine=>({id:'c1',quantity,unitPriceKobo:100,lineTotalKobo:quantity*100,product:{id:'p1',name:'Card',type:'standard',active:true},variant:{id:'v1',colorName:'Black',colorHex:'#000000',stockQty:99,active:true,imageUrls:[]},customUsername:null,preferredColor:null,instructions:null,artworkUrl:null})
const cart=(quantity:number):ServerCart=>({id:'cart',items:quantity?[line(quantity)]:[],itemCount:quantity,subtotalKobo:quantity*100})
beforeEach(()=>{localStorage.clear();useCartStore.setState({items:[{productId:'p1',variantId:'v1',colorName:'Black',quantity:2}]});vi.restoreAllMocks()})
it('reconciles an acknowledged server write even when its response was lost',async()=>{let qty=1;const get=vi.spyOn(commerce,'cart').mockImplementation(async()=>cart(qty));const patch=vi.spyOn(commerce,'update').mockImplementation(async(_,target)=>{qty=target;throw new Error('response lost')});await syncGuestCart('u1');expect(qty).toBe(3);expect(patch).toHaveBeenCalledTimes(1);expect(get).toHaveBeenCalledTimes(2);expect(useCartStore.getState().items).toEqual([])})
it('keeps the absolute target across retries after a failed write',async()=>{let qty=1;vi.spyOn(commerce,'cart').mockImplementation(async()=>cart(qty));const patch=vi.spyOn(commerce,'update').mockRejectedValueOnce(new Error('offline')).mockImplementation(async(_,target)=>{qty=target;return cart(qty)});await expect(syncGuestCart('u1')).rejects.toThrow('offline');expect(useCartStore.getState().items).toHaveLength(1);await syncGuestCart('u1');expect(qty).toBe(3);expect(patch).toHaveBeenLastCalledWith('c1',3)})
it('does not resume terminal payments or accept unsafe redirect schemes',()=>{for(const status of ['success','failed','reversed'])expect(canPay({payment:{status},status:'processing'} as Order)).toBe(false);expect(canPay({payment:{status:'pending'},status:'cancelled'} as Order)).toBe(false);expect(paymentUrl('javascript:alert(1)')).toBe(null);expect(paymentUrl('https://sandbox.example/pay')).toBe('https://sandbox.example/pay')})

it('does not replay an ambiguous add request that might still commit',async()=>{vi.spyOn(commerce,'cart').mockResolvedValue(cart(0));const add=vi.spyOn(commerce,'add').mockRejectedValue(new Error('response lost'));await expect(syncGuestCart('u1')).rejects.toThrow();await expect(syncGuestCart('u1')).rejects.toThrow('unconfirmed');expect(add).toHaveBeenCalledTimes(1)})
