/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplateRouteImport } from './routes/template'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as StoreCartRouteImport } from './routes/store/cart'
import { Route as DashboardAppearanceRouteImport } from './routes/dashboard/appearance'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthTokenRouteImport } from './routes/auth/$token'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/auth/reset-password/$token'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const TemplateRoute = TemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/store/cart',
  path: '/store/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAppearanceRoute = DashboardAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTokenRoute = AuthTokenRouteImport.update({
  id: '/auth/$token',
  path: '/auth/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/auth/reset-password/$token',
  path: '/auth/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$username': typeof UsernameRoute
  '/contact-us': typeof ContactUsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/template': typeof TemplateRoute
  '/auth/$token': typeof AuthTokenRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/appearance': typeof DashboardAppearanceRoute
  '/store/cart': typeof StoreCartRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/store/': typeof StoreIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/contact-us': typeof ContactUsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/template': typeof TemplateRoute
  '/auth/$token': typeof AuthTokenRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/appearance': typeof DashboardAppearanceRoute
  '/store/cart': typeof StoreCartRoute
  '/dashboard': typeof DashboardIndexRoute
  '/store': typeof StoreIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$username': typeof UsernameRoute
  '/contact-us': typeof ContactUsRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/template': typeof TemplateRoute
  '/auth/$token': typeof AuthTokenRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/appearance': typeof DashboardAppearanceRoute
  '/store/cart': typeof StoreCartRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/store/': typeof StoreIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/$username'
    | '/contact-us'
    | '/onboarding'
    | '/pricing'
    | '/template'
    | '/auth/$token'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/appearance'
    | '/store/cart'
    | '/dashboard/'
    | '/store/'
    | '/auth/google/callback'
    | '/auth/reset-password/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/contact-us'
    | '/onboarding'
    | '/pricing'
    | '/template'
    | '/auth/$token'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/appearance'
    | '/store/cart'
    | '/dashboard'
    | '/store'
    | '/auth/google/callback'
    | '/auth/reset-password/$token'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/$username'
    | '/contact-us'
    | '/onboarding'
    | '/pricing'
    | '/template'
    | '/auth/$token'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/appearance'
    | '/store/cart'
    | '/dashboard/'
    | '/store/'
    | '/auth/google/callback'
    | '/auth/reset-password/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  UsernameRoute: typeof UsernameRoute
  ContactUsRoute: typeof ContactUsRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  TemplateRoute: typeof TemplateRoute
  AuthTokenRoute: typeof AuthTokenRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreIndexRoute: typeof StoreIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/template': {
      id: '/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof TemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/store/cart': {
      id: '/store/cart'
      path: '/store/cart'
      fullPath: '/store/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/appearance': {
      id: '/dashboard/appearance'
      path: '/appearance'
      fullPath: '/dashboard/appearance'
      preLoaderRoute: typeof DashboardAppearanceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$token': {
      id: '/auth/$token'
      path: '/auth/$token'
      fullPath: '/auth/$token'
      preLoaderRoute: typeof AuthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/auth/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAppearanceRoute: typeof DashboardAppearanceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAppearanceRoute: DashboardAppearanceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  UsernameRoute: UsernameRoute,
  ContactUsRoute: ContactUsRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  TemplateRoute: TemplateRoute,
  AuthTokenRoute: AuthTokenRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  StoreCartRoute: StoreCartRoute,
  StoreIndexRoute: StoreIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
