/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplateRouteImport } from './routes/template'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as StoreCartRouteImport } from './routes/store/cart'
import { Route as OnboardingUsernameRouteImport } from './routes/onboarding/username'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding/profile'
import { Route as OnboardingPlatformsRouteImport } from './routes/onboarding/platforms'
import { Route as OnboardingLinksRouteImport } from './routes/onboarding/links'
import { Route as OnboardingGoalRouteImport } from './routes/onboarding/goal'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding/complete'
import { Route as OnboardingCategoryRouteImport } from './routes/onboarding/category'
import { Route as DashboardStoreRouteImport } from './routes/dashboard/store'
import { Route as DashboardStatisticsRouteImport } from './routes/dashboard/statistics'
import { Route as DashboardAppearanceRouteImport } from './routes/dashboard/appearance'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthTokenRouteImport } from './routes/auth/$token'
import { Route as AuthResetPasswordTokenRouteImport } from './routes/auth/reset-password/$token'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const TemplateRoute = TemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/store/cart',
  path: '/store/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingUsernameRoute = OnboardingUsernameRouteImport.update({
  id: '/username',
  path: '/username',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingPlatformsRoute = OnboardingPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingLinksRoute = OnboardingLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingGoalRoute = OnboardingGoalRouteImport.update({
  id: '/goal',
  path: '/goal',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingCategoryRoute = OnboardingCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const DashboardStoreRoute = DashboardStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStatisticsRoute = DashboardStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAppearanceRoute = DashboardAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTokenRoute = AuthTokenRouteImport.update({
  id: '/auth/$token',
  path: '/auth/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordTokenRoute = AuthResetPasswordTokenRouteImport.update({
  id: '/auth/reset-password/$token',
  path: '/auth/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/$username': typeof UsernameRoute
  '/contact-us': typeof ContactUsRoute
  '/pricing': typeof PricingRoute
  '/template': typeof TemplateRoute
  '/auth/$token': typeof AuthTokenRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/appearance': typeof DashboardAppearanceRoute
  '/dashboard/statistics': typeof DashboardStatisticsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/onboarding/category': typeof OnboardingCategoryRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/links': typeof OnboardingLinksRoute
  '/onboarding/platforms': typeof OnboardingPlatformsRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/username': typeof OnboardingUsernameRoute
  '/store/cart': typeof StoreCartRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/store/': typeof StoreIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/contact-us': typeof ContactUsRoute
  '/pricing': typeof PricingRoute
  '/template': typeof TemplateRoute
  '/auth/$token': typeof AuthTokenRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/appearance': typeof DashboardAppearanceRoute
  '/dashboard/statistics': typeof DashboardStatisticsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/onboarding/category': typeof OnboardingCategoryRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/links': typeof OnboardingLinksRoute
  '/onboarding/platforms': typeof OnboardingPlatformsRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/username': typeof OnboardingUsernameRoute
  '/store/cart': typeof StoreCartRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/store': typeof StoreIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/$username': typeof UsernameRoute
  '/contact-us': typeof ContactUsRoute
  '/pricing': typeof PricingRoute
  '/template': typeof TemplateRoute
  '/auth/$token': typeof AuthTokenRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/appearance': typeof DashboardAppearanceRoute
  '/dashboard/statistics': typeof DashboardStatisticsRoute
  '/dashboard/store': typeof DashboardStoreRoute
  '/onboarding/category': typeof OnboardingCategoryRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/links': typeof OnboardingLinksRoute
  '/onboarding/platforms': typeof OnboardingPlatformsRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/onboarding/username': typeof OnboardingUsernameRoute
  '/store/cart': typeof StoreCartRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/store/': typeof StoreIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/auth/reset-password/$token': typeof AuthResetPasswordTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/$username'
    | '/contact-us'
    | '/pricing'
    | '/template'
    | '/auth/$token'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/appearance'
    | '/dashboard/statistics'
    | '/dashboard/store'
    | '/onboarding/category'
    | '/onboarding/complete'
    | '/onboarding/goal'
    | '/onboarding/links'
    | '/onboarding/platforms'
    | '/onboarding/profile'
    | '/onboarding/username'
    | '/store/cart'
    | '/dashboard/'
    | '/onboarding/'
    | '/store/'
    | '/auth/google/callback'
    | '/auth/reset-password/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/contact-us'
    | '/pricing'
    | '/template'
    | '/auth/$token'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/appearance'
    | '/dashboard/statistics'
    | '/dashboard/store'
    | '/onboarding/category'
    | '/onboarding/complete'
    | '/onboarding/goal'
    | '/onboarding/links'
    | '/onboarding/platforms'
    | '/onboarding/profile'
    | '/onboarding/username'
    | '/store/cart'
    | '/dashboard'
    | '/onboarding'
    | '/store'
    | '/auth/google/callback'
    | '/auth/reset-password/$token'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/$username'
    | '/contact-us'
    | '/pricing'
    | '/template'
    | '/auth/$token'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/appearance'
    | '/dashboard/statistics'
    | '/dashboard/store'
    | '/onboarding/category'
    | '/onboarding/complete'
    | '/onboarding/goal'
    | '/onboarding/links'
    | '/onboarding/platforms'
    | '/onboarding/profile'
    | '/onboarding/username'
    | '/store/cart'
    | '/dashboard/'
    | '/onboarding/'
    | '/store/'
    | '/auth/google/callback'
    | '/auth/reset-password/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  UsernameRoute: typeof UsernameRoute
  ContactUsRoute: typeof ContactUsRoute
  PricingRoute: typeof PricingRoute
  TemplateRoute: typeof TemplateRoute
  AuthTokenRoute: typeof AuthTokenRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreIndexRoute: typeof StoreIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  AuthResetPasswordTokenRoute: typeof AuthResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/template': {
      id: '/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof TemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/store/cart': {
      id: '/store/cart'
      path: '/store/cart'
      fullPath: '/store/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/username': {
      id: '/onboarding/username'
      path: '/username'
      fullPath: '/onboarding/username'
      preLoaderRoute: typeof OnboardingUsernameRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/platforms': {
      id: '/onboarding/platforms'
      path: '/platforms'
      fullPath: '/onboarding/platforms'
      preLoaderRoute: typeof OnboardingPlatformsRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/links': {
      id: '/onboarding/links'
      path: '/links'
      fullPath: '/onboarding/links'
      preLoaderRoute: typeof OnboardingLinksRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/goal': {
      id: '/onboarding/goal'
      path: '/goal'
      fullPath: '/onboarding/goal'
      preLoaderRoute: typeof OnboardingGoalRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/category': {
      id: '/onboarding/category'
      path: '/category'
      fullPath: '/onboarding/category'
      preLoaderRoute: typeof OnboardingCategoryRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/dashboard/store': {
      id: '/dashboard/store'
      path: '/store'
      fullPath: '/dashboard/store'
      preLoaderRoute: typeof DashboardStoreRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/statistics': {
      id: '/dashboard/statistics'
      path: '/statistics'
      fullPath: '/dashboard/statistics'
      preLoaderRoute: typeof DashboardStatisticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/appearance': {
      id: '/dashboard/appearance'
      path: '/appearance'
      fullPath: '/dashboard/appearance'
      preLoaderRoute: typeof DashboardAppearanceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$token': {
      id: '/auth/$token'
      path: '/auth/$token'
      fullPath: '/auth/$token'
      preLoaderRoute: typeof AuthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/$token': {
      id: '/auth/reset-password/$token'
      path: '/auth/reset-password/$token'
      fullPath: '/auth/reset-password/$token'
      preLoaderRoute: typeof AuthResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAppearanceRoute: typeof DashboardAppearanceRoute
  DashboardStatisticsRoute: typeof DashboardStatisticsRoute
  DashboardStoreRoute: typeof DashboardStoreRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAppearanceRoute: DashboardAppearanceRoute,
  DashboardStatisticsRoute: DashboardStatisticsRoute,
  DashboardStoreRoute: DashboardStoreRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingCategoryRoute: typeof OnboardingCategoryRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingGoalRoute: typeof OnboardingGoalRoute
  OnboardingLinksRoute: typeof OnboardingLinksRoute
  OnboardingPlatformsRoute: typeof OnboardingPlatformsRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  OnboardingUsernameRoute: typeof OnboardingUsernameRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingCategoryRoute: OnboardingCategoryRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingGoalRoute: OnboardingGoalRoute,
  OnboardingLinksRoute: OnboardingLinksRoute,
  OnboardingPlatformsRoute: OnboardingPlatformsRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  OnboardingUsernameRoute: OnboardingUsernameRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  UsernameRoute: UsernameRoute,
  ContactUsRoute: ContactUsRoute,
  PricingRoute: PricingRoute,
  TemplateRoute: TemplateRoute,
  AuthTokenRoute: AuthTokenRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  StoreCartRoute: StoreCartRoute,
  StoreIndexRoute: StoreIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  AuthResetPasswordTokenRoute: AuthResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
